export interface Exhibition {
  id: string;
  title: string;
  slug: string;
  dates: string;
  startDate: string;
  endDate: string;
  venue: string;
  city: string;
  country: string;
  industry: string;
  description: string;
  highlights: string[];
  exhibitors: number;
  visitors: string;
  organizer: string;
  website: string;
  color: string;
}

export const exhibitions: Exhibition[] = [
  // ── MARCH ──
  {
    id: "1",
    title: "2026 Global Ocean City Food Expo",
    slug: "global-ocean-city-food-expo-2026",
    dates: "March 29–31, 2026",
    startDate: "2026-03-29",
    endDate: "2026-03-31",
    venue: "Xiamen International Conference & Exhibition Center",
    city: "Xiamen",
    country: "China",
    industry: "Food & Beverage",
    description:
      "The Global Ocean City Food Expo brings together leading food and beverage manufacturers, distributors, and buyers from around the world. Explore the latest in seafood processing, agricultural products, food technology, and sustainable packaging solutions.",
    highlights: [
      "500+ exhibitors from 30+ countries",
      "Live seafood & food processing demos",
      "International chef competition",
      "B2B matchmaking sessions",
      "Sustainable food packaging forum",
    ],
    exhibitors: 500,
    visitors: "30,000+",
    organizer: "China Food Industry Association",
    website: "https://www.winbtb.com/expo/114",
    color: "#0EA5E9",
  },

  // ── MAY ──
  {
    id: "2",
    title: "The 99th China Automobile Parts Fair",
    slug: "99th-china-automobile-parts-fair-2026",
    dates: "May 13–15, 2026",
    startDate: "2026-05-13",
    endDate: "2026-05-15",
    venue: "Chongqing International Expo Center",
    city: "Chongqing",
    country: "China",
    industry: "Automotive",
    description:
      "One of the largest and most influential auto parts exhibitions in China. The 99th edition covers the full spectrum of automotive components, EV parts, diagnostic equipment, and aftermarket services.",
    highlights: [
      "2,000+ exhibitors",
      "EV & new energy vehicle parts zone",
      "OEM procurement matchmaking",
      "Automotive technology summit",
      "Live product demonstrations",
    ],
    exhibitors: 2000,
    visitors: "80,000+",
    organizer: "China Machinery Industry Federation",
    website: "https://www.winbtb.com/exhibit/118",
    color: "#DC2626",
  },

  // ── AUGUST ──
  {
    id: "3",
    title: "China (Wuxi) Industrial Valve Expo",
    slug: "china-wuxi-industrial-valve-expo-2026",
    dates: "August 20–22, 2026",
    startDate: "2026-08-20",
    endDate: "2026-08-22",
    venue: "Wuxi Taihu International Expo Center",
    city: "Wuxi",
    country: "China",
    industry: "Industrial",
    description:
      "The premier industrial valve exhibition in China, showcasing the latest in valve manufacturing, flow control technology, actuator systems, and piping solutions for oil & gas, chemical, and water treatment industries.",
    highlights: [
      "300+ valve manufacturers",
      "Flow control technology showcase",
      "International procurement meeting",
      "Technical seminars & workshops",
      "New product launch zone",
    ],
    exhibitors: 300,
    visitors: "15,000+",
    organizer: "Wuxi Valve Industry Association",
    website: "https://www.winbtb.com/expo/138",
    color: "#7C3AED",
  },

  // ── SEPTEMBER ──
  {
    id: "7",
    title: "China International Beauty Expo (CIBE) — Autumn",
    slug: "cibe-guangzhou-autumn-2026",
    dates: "September 4–5, 2026",
    startDate: "2026-09-04",
    endDate: "2026-09-05",
    venue: "China Import & Export Fair Complex (Pazhou)",
    city: "Guangzhou",
    country: "China",
    industry: "Health & Beauty",
    description:
      "One of China's largest beauty and cosmetics trade shows, featuring skincare, makeup, professional beauty equipment, packaging, and wellness products from hundreds of brands across Asia and beyond.",
    highlights: [
      "1,500+ beauty brands",
      "Skincare & cosmetics showcase",
      "Professional beauty equipment zone",
      "Packaging & OEM/ODM pavilion",
      "Live beauty demonstrations",
    ],
    exhibitors: 1500,
    visitors: "40,000+",
    organizer: "China Beauty Expo Committee",
    website: "https://www.cibeexpo.com",
    color: "#EC4899",
  },
  {
    id: "8",
    title: "The 58th CIFF Shanghai — China International Furniture Fair",
    slug: "ciff-shanghai-2026",
    dates: "September 5–8, 2026",
    startDate: "2026-09-05",
    endDate: "2026-09-08",
    venue: "National Exhibition and Convention Center (Shanghai Hongqiao)",
    city: "Shanghai",
    country: "China",
    industry: "Home & Garden",
    description:
      "One of the world's largest furniture trade fairs covering home furniture, office furniture, outdoor furniture, home decor, and furniture machinery. The 58th edition at Shanghai Hongqiao.",
    highlights: [
      "3,000+ exhibitors",
      "Home, office & outdoor furniture zones",
      "Furniture machinery & woodworking expo",
      "Design-driven innovation pavilion",
      "International sourcing hub",
    ],
    exhibitors: 3000,
    visitors: "150,000+",
    organizer: "China Foreign Trade Centre",
    website: "https://en.ciff-sh.com",
    color: "#92400E",
  },
  {
    id: "9",
    title: "CIFTIS 2026 — China International Fair for Trade in Services",
    slug: "ciftis-2026-beijing",
    dates: "September 9–13, 2026",
    startDate: "2026-09-09",
    endDate: "2026-09-13",
    venue: "China National Convention Center & Shougang Park",
    city: "Beijing",
    country: "China",
    industry: "Trade & Investment",
    description:
      "One of China's top three exhibition platforms alongside Canton Fair and CIIE. CIFTIS is the only all-inclusive international fair focused on trade in services, covering finance, tourism, education, healthcare, technology, and logistics.",
    highlights: [
      "80+ countries participating",
      "Finance, tech, healthcare & logistics sectors",
      "Global services trade summit",
      "Digital services innovation zone",
      "B2B matchmaking & investment forums",
    ],
    exhibitors: 2000,
    visitors: "200,000+",
    organizer: "Ministry of Commerce of China",
    website: "https://www.ciftis.org/en/",
    color: "#B91C1C",
  },
  {
    id: "10",
    title: "CIOE 2026 — China International Optoelectronic Exposition",
    slug: "cioe-2026-shenzhen",
    dates: "September 9–11, 2026",
    startDate: "2026-09-09",
    endDate: "2026-09-11",
    venue: "Shenzhen World Exhibition & Convention Center",
    city: "Shenzhen",
    country: "China",
    industry: "Electronics",
    description:
      "The world's largest optoelectronics exhibition, covering optical communications, lasers, infrared technology, precision optics, and photonics. Over 3,000 exhibitors and 100,000+ professional visitors annually.",
    highlights: [
      "3,000+ exhibitors from 90+ countries",
      "Optical communications & networking",
      "Laser & infrared technology zone",
      "Precision optics & photonics",
      "Emerging technologies forum",
    ],
    exhibitors: 3000,
    visitors: "100,000+",
    organizer: "CIOE Organizing Committee",
    website: "https://www.cioe.cn/en/",
    color: "#0369A1",
  },
  {
    id: "11",
    title: "23rd China-ASEAN Expo (CAEXPO)",
    slug: "caexpo-2026-nanning",
    dates: "September 17–21, 2026",
    startDate: "2026-09-17",
    endDate: "2026-09-21",
    venue: "Nanning International Convention & Exhibition Center",
    city: "Nanning",
    country: "China",
    industry: "Trade & Investment",
    description:
      "A premier trade platform between China and ASEAN countries, covering commodities trade, investment cooperation, advanced technology, and services trade. Co-hosted by China's Ministry of Commerce and ASEAN member states.",
    highlights: [
      "11 ASEAN countries + China",
      "Commodities trade pavilion",
      "Investment cooperation forums",
      "Advanced technology showcase",
      "Services trade promotion zone",
    ],
    exhibitors: 3000,
    visitors: "100,000+",
    organizer: "CAEXPO Secretariat",
    website: "https://www.caexpo.org.cn/en-US",
    color: "#059669",
  },
  {
    id: "12",
    title: "China (Linyi) International Trade & Logistics Fair",
    slug: "linyi-trade-logistics-fair-2026",
    dates: "September 20–22, 2026",
    startDate: "2026-09-20",
    endDate: "2026-09-22",
    venue: "Linyi International Convention & Exhibition Center",
    city: "Linyi",
    country: "China",
    industry: "Logistics",
    description:
      "Showcasing Linyi's strength as one of China's largest wholesale and logistics hubs, featuring small commodities, building materials, hardware, and e-commerce solutions. Linyi is known as 'China's Logistics Capital.'",
    highlights: [
      "5,000+ exhibitors",
      "Small commodities & hardware",
      "E-commerce & logistics solutions",
      "Building materials showcase",
      "Cross-border trade forums",
    ],
    exhibitors: 5000,
    visitors: "200,000+",
    organizer: "Linyi Municipal Government",
    website: "https://www.lyice.com",
    color: "#D97706",
  },
  {
    id: "13",
    title: "Weifang International Agricultural Machinery Exhibition",
    slug: "weifang-agricultural-machinery-2026",
    dates: "September 21–22, 2026",
    startDate: "2026-09-21",
    endDate: "2026-09-22",
    venue: "Weifang Luguang Exhibition Center",
    city: "Weifang",
    country: "China",
    industry: "Agriculture",
    description:
      "Focused on agricultural machinery, farming equipment, smart agriculture technology, and rural revitalization solutions. Weifang is a major agricultural production base in Shandong Province.",
    highlights: [
      "800+ agricultural machinery exhibitors",
      "Smart farming technology demos",
      "Live field demonstrations",
      "Rural revitalization forum",
      "Drone & precision agriculture zone",
    ],
    exhibitors: 800,
    visitors: "60,000+",
    organizer: "Weifang Municipal Government",
    website: "https://www.wfice.com",
    color: "#65A30D",
  },
  {
    id: "4",
    title: "The 5th Global Digital Trade Expo",
    slug: "5th-global-digital-trade-expo-2026",
    dates: "September 23–27, 2026",
    startDate: "2026-09-23",
    endDate: "2026-09-27",
    venue: "Hangzhou International Expo Center",
    city: "Hangzhou",
    country: "China",
    industry: "Digital Trade",
    description:
      "Asia's leading digital trade exhibition, featuring cross-border e-commerce platforms, AI-powered trade solutions, fintech, blockchain logistics, and smart supply chain innovations.",
    highlights: [
      "1,000+ global exhibitors",
      "Cross-border e-commerce forum",
      "AI & blockchain in trade summit",
      "Digital payment solutions zone",
      "Startup innovation pavilion",
    ],
    exhibitors: 1000,
    visitors: "100,000+",
    organizer: "Hangzhou Municipal Government",
    website: "https://www.winbtb.com/expo/129",
    color: "#2563EB",
  },

  // ── OCTOBER ──
  {
    id: "14",
    title: "HOTELEX Shenzhen — International Hotel & Catering Exhibition",
    slug: "hotelex-shenzhen-2026",
    dates: "October 13–15, 2026",
    startDate: "2026-10-13",
    endDate: "2026-10-15",
    venue: "Shenzhen World Exhibition & Convention Center",
    city: "Shenzhen",
    country: "China",
    industry: "Hospitality",
    description:
      "A major hospitality industry event featuring hotel supplies, catering equipment, food and beverage, coffee and tea, bakery equipment, and restaurant technology. 2,500+ exhibitors from around the world.",
    highlights: [
      "2,500+ exhibitors",
      "Hotel supplies & catering equipment",
      "Coffee, tea & bakery expo",
      "Restaurant technology showcase",
      "Hosted buyer programme",
    ],
    exhibitors: 2500,
    visitors: "80,000+",
    organizer: "Sinoexpo Informa Markets",
    website: "https://www.hotelex.com",
    color: "#7C2D12",
  },
  {
    id: "15",
    title: "Hong Kong Electronics Fair — Autumn Edition",
    slug: "hk-electronics-fair-autumn-2026",
    dates: "October 13–16, 2026",
    startDate: "2026-10-13",
    endDate: "2026-10-16",
    venue: "Hong Kong Convention and Exhibition Centre (HKCEC)",
    city: "Hong Kong",
    country: "China",
    industry: "Electronics",
    description:
      "Asia's leading electronics trade fair featuring consumer electronics, smart home devices, audio-visual products, and electronic components. HKTDC's flagship electronics event.",
    highlights: [
      "2,800+ exhibitors from 19 countries",
      "Consumer electronics & smart home",
      "Audio-visual & digital entertainment",
      "Electronic components zone",
      "Startup & innovation pavilion",
    ],
    exhibitors: 2800,
    visitors: "88,000+",
    organizer: "HKTDC",
    website: "https://www.hktdc.com/event/hkelectronicsfairae/en",
    color: "#1D4ED8",
  },
  {
    id: "16",
    title: "China (Guzhen) International Lighting Fair — Autumn",
    slug: "guzhen-lighting-fair-autumn-2026",
    dates: "October 22–25, 2026",
    startDate: "2026-10-22",
    endDate: "2026-10-25",
    venue: "Guzhen Convention & Exhibition Center",
    city: "Zhongshan",
    country: "China",
    industry: "Lighting",
    description:
      "The world's largest lighting industry trade fair. Guzhen is known as the 'Lighting Capital of China,' producing over 70% of China's lighting products. Features indoor, outdoor, LED, and smart lighting.",
    highlights: [
      "2,000+ lighting manufacturers",
      "Indoor & outdoor lighting zones",
      "LED & smart lighting technology",
      "Lighting components & design",
      "Factory visits & specialty zones",
    ],
    exhibitors: 2000,
    visitors: "100,000+",
    organizer: "Guzhen Lighting Fair Committee",
    website: "https://en.jiagle.com/lighting-fair/",
    color: "#EAB308",
  },
  {
    id: "17",
    title: "Shantou International Toys & Gifts Fair",
    slug: "shantou-toys-gifts-fair-2026",
    dates: "October 29 – November 1, 2026",
    startDate: "2026-10-29",
    endDate: "2026-11-01",
    venue: "Shantou International Convention & Exhibition Center",
    city: "Shantou",
    country: "China",
    industry: "Toys & Gifts",
    description:
      "Showcases toys, models, educational toys, outdoor play equipment, and gift items. Chenghai district in Shantou produces over 70% of China's toy exports — the 'Toy Capital of China.'",
    highlights: [
      "1,000+ toy & gift exhibitors",
      "Educational & STEM toys zone",
      "Outdoor play equipment",
      "Models & collectibles",
      "Chenghai factory tours",
    ],
    exhibitors: 1000,
    visitors: "50,000+",
    organizer: "Shantou Fair Committee",
    website: "https://www.sttoyfair.com",
    color: "#F97316",
  },
  {
    id: "18",
    title: "C-TOUCH & DISPLAY Shenzhen",
    slug: "c-touch-display-shenzhen-2026",
    dates: "October 27–29, 2026",
    startDate: "2026-10-27",
    endDate: "2026-10-29",
    venue: "Shenzhen World Exhibition & Convention Center",
    city: "Shenzhen",
    country: "China",
    industry: "Electronics",
    description:
      "Focused on touch screen technology, display panels, flexible electronics, film materials, and related manufacturing equipment. Concurrent with the Shenzhen International Flexible Printed Electronics Exhibition.",
    highlights: [
      "500+ touch & display exhibitors",
      "Touch screen technology showcase",
      "Display panel innovations",
      "Flexible electronics pavilion",
      "Film & materials expo",
    ],
    exhibitors: 500,
    visitors: "30,000+",
    organizer: "Reed Exhibitions",
    website: "https://www.c-touch.cn",
    color: "#6366F1",
  },
  {
    id: "19",
    title: "Taizhou International Plastics & Molding Exhibition",
    slug: "taizhou-plastics-molding-2026",
    dates: "October 18–19, 2026",
    startDate: "2026-10-18",
    endDate: "2026-10-19",
    venue: "Taizhou International Convention & Exhibition Center",
    city: "Taizhou",
    country: "China",
    industry: "Manufacturing",
    description:
      "Taizhou is a major manufacturing hub for plastic molds and injection molding. The exhibition covers plastic raw materials, molding machines, molds, and finished plastic products. Known as the 'Mold Capital of China.'",
    highlights: [
      "600+ molding industry exhibitors",
      "Injection molding machines",
      "Plastic raw materials & additives",
      "Mold design & manufacturing",
      "Finished plastic products showcase",
    ],
    exhibitors: 600,
    visitors: "30,000+",
    organizer: "Taizhou Exhibition Bureau",
    website: "https://www.tzplastic.com",
    color: "#0891B2",
  },
  {
    id: "5",
    title: "The 26th China Anping International Wire Mesh Fair",
    slug: "26th-china-anping-wire-mesh-fair-2026",
    dates: "October 22–24, 2026",
    startDate: "2026-10-22",
    endDate: "2026-10-24",
    venue: "Anping County Exhibition Center",
    city: "Hengshui",
    country: "China",
    industry: "Manufacturing",
    description:
      "The world's largest wire mesh exhibition, held in Anping — the Wire Mesh Capital of China. Features industrial wire mesh, fencing, filters, metal processing equipment, and construction mesh products.",
    highlights: [
      "800+ exhibitors from 50+ countries",
      "Wire mesh manufacturing demos",
      "International trade forums",
      "Industrial filtration showcase",
      "Construction mesh innovation zone",
    ],
    exhibitors: 800,
    visitors: "50,000+",
    organizer: "Anping County Government",
    website: "https://www.winbtb.com/expo/103",
    color: "#D97706",
  },
  {
    id: "6",
    title: "The 31st Macao International Trade & Investment Fair",
    slug: "31st-macao-mif-2026",
    dates: "October 21–24, 2026",
    startDate: "2026-10-21",
    endDate: "2026-10-24",
    venue: "Cotai Expo, The Venetian Macao",
    city: "Macao",
    country: "China",
    industry: "Trade & Investment",
    description:
      "Macao's flagship international trade and investment event, connecting businesses from China, Portuguese-speaking countries, and Southeast Asia. Features investment promotion, trade matching, and economic cooperation forums.",
    highlights: [
      "2,000+ exhibitors",
      "Investment promotion conferences",
      "Portuguese-speaking countries pavilion",
      "Business matching platform",
      "Guangdong-Hong Kong-Macao cooperation zone",
    ],
    exhibitors: 2000,
    visitors: "60,000+",
    organizer: "Macao Trade and Investment Promotion Institute",
    website: "https://www.winbtb.com/expo/133",
    color: "#059669",
  },

  // ── DECEMBER ──
  {
    id: "20",
    title: "MIECF — Macao International Environmental Co-operation Forum",
    slug: "miecf-macao-winter-2026",
    dates: "December 3–5, 2026",
    startDate: "2026-12-03",
    endDate: "2026-12-05",
    venue: "Cotai Expo, The Venetian Macao",
    city: "Macao",
    country: "China",
    industry: "Environment",
    description:
      "Focused on environmental protection technologies, green energy, waste management, and sustainable development solutions. Connects international environmental businesses with the Greater China market.",
    highlights: [
      "Environmental technology showcase",
      "Green energy & clean tech",
      "Waste management solutions",
      "Sustainable development forums",
      "International green partnerships",
    ],
    exhibitors: 400,
    visitors: "20,000+",
    organizer: "Macao SAR Government",
    website: "https://www.miecf.com",
    color: "#16A34A",
  },
];

export function getExhibitionById(id: string): Exhibition | undefined {
  return exhibitions.find((e) => e.id === id || e.slug === id);
}

export function getIndustries(): string[] {
  return [...new Set(exhibitions.map((e) => e.industry))].sort();
}

export function getCities(): string[] {
  return [...new Set(exhibitions.map((e) => e.city))].sort();
}
