export interface FeaturedEvent {
  id: string;
  title: string;
  subtitle: string;
  dates: string;
  venue: string;
  city: string;
  highlights: string[];
  benefits: string[];
  eligibility: string[];
  image: string;
  color: string;
  gradient: string;
  slug: string;
}

export const featuredEvents: FeaturedEvent[] = [
  {
    id: "ciff",
    title: "CIFF Shanghai 2026",
    subtitle: "China International Furniture Fair",
    dates: "September 4–6, 2026",
    venue: "National Exhibition and Convention Center",
    city: "Shanghai, China",
    highlights: [
      "3,000+ leading Chinese furniture manufacturers",
      "Home, sleep, décor, outdoor, office & original design",
      "Woodworking machinery & furniture manufacturing",
      "International Buyer Invitation Programme",
    ],
    benefits: [
      "2 nights complimentary hotel accommodation",
      "RMB 600 transportation reimbursement",
      "Complimentary breakfast",
      "One-on-one business matching",
    ],
    eligibility: [
      "Priority for buyers from Europe & the Americas",
      "Exhibition visit Sep 5–6 required",
      "Hotel check-in Sep 4",
    ],
    image: "/images/events/ciff-shanghai-2026.jpg",
    color: "#B91C1C",
    gradient: "from-red-700 via-red-600 to-orange-500",
    slug: "ciff-shanghai-2026",
  },
  {
    id: "ciftis",
    title: "CIFTIS 2026",
    subtitle: "China International Fair for Trade in Services",
    dates: "September 9–13, 2026",
    venue: "Shougang Park, Beijing",
    city: "Beijing, China",
    highlights: [
      "National-level official service trade platform",
      "2,000+ onsite exhibitors, 5,000+ online",
      "\"Business Appointment\" system for efficient 1-on-1 talks",
      "Covers 85+ countries & regions",
    ],
    benefits: [
      "Travel subsidy",
      "Pre-scheduled one-on-one business matching",
      "VIP access & priority service",
      "Latest industry insights & solutions",
      "Free on-site consultation",
    ],
    eligibility: [
      "Age: 26–60",
      "Visa: Non-student",
      "Business: Telecom / IT / Digital services / International trade",
      "Valid business license required",
    ],
    image: "/images/events/ciftis-2026.jpg",
    color: "#1D4ED8",
    gradient: "from-cyan-700 via-cyan-600 to-teal-500",
    slug: "ciftis-2026-beijing",
  },
  {
    id: "digital-energy",
    title: "International Digital Energy Expo 2026",
    subtitle: "Digital Energy · Green Future · Shared Development",
    dates: "September 14–15, 2026",
    venue: "Shenzhen Convention & Exhibition Center (Futian)",
    city: "Shenzhen, China",
    highlights: [
      "50,000 sqm exhibition space",
      "Green power, smart grid, energy storage, digital tech",
      "Overseas livestreaming to global audiences",
      "Digital energy salon & interactive displays",
    ],
    benefits: [
      "One night hotel accommodation",
      "Shuttle bus & travel reimbursement",
      "VIP badge access",
      "1-on-1 business matchmaking",
      "Breakfast & lunch during the expo",
    ],
    eligibility: [
      "Delegation option: Sep 14–15 or Sep 15–16",
      "Open to international delegates",
    ],
    image: "/images/events/digital-energy-expo-2026.jpg",
    color: "#16A34A",
    gradient: "from-green-600 via-emerald-500 to-lime-400",
    slug: "digital-energy-expo-2026",
  },
  {
    id: "linyi-general",
    title: "8th China (Linyi) General Merchandise & Cleaning Products Expo",
    subtitle: "and The 3rd Lu Exhibition International Trade Selection Fair",
    dates: "September 7–9, 2026",
    venue: "Linyi International Expo Center",
    city: "Linyi, China",
    highlights: [
      "60,000 sqm, 2,500+ booths, 1,800+ exhibitors",
      "Northern China's largest general merchandise expo",
      "One-stop sourcing: plastics, hardware, kitchenware, home textiles",
      "Supported by Linyi — China's Logistics Capital",
    ],
    benefits: [
      "100 RMB bonus + full ticket reimbursement",
      "Pre-scheduled one-on-one business matching",
      "VIP access & priority service",
      "Latest industry insights & solutions",
      "Free on-site consultation",
    ],
    eligibility: [
      "Age: 26–60",
      "Visa: Non-student",
      "Merchants need passports, visas, overseas business cards",
      "Purchasing intent required",
    ],
    image: "/images/events/linyi-general-expo-2026.jpg",
    color: "#EA580C",
    gradient: "from-orange-600 via-orange-500 to-amber-400",
    slug: "linyi-trade-logistics-fair-2026",
  },
  {
    id: "linyi-hardware",
    title: "Linyi Hardware Expo 2026",
    subtitle: "2025 Linyi Mall International Buyer's Conference — Hedong Hardware Session",
    dates: "September 20–22, 2026",
    venue: "Linyi Hardware City International Procurement Exhibition Hall",
    city: "Linyi, China",
    highlights: [
      "Hand tools, electric tools, air tools",
      "Mechanical & electrical products",
      "International buyer conference",
      "Work visa preferred — any nationality welcome",
    ],
    benefits: [
      "Free admission ticket",
      "Free 2 nights hotel accommodation",
      "Free food",
      "Free train or flight ticket (from China or abroad)",
      "Bonus subsidy: 150–200 RMB based on visa type",
    ],
    eligibility: [
      "Work visa preferred",
      "Any nationality",
      "Buyers in hardware-related industries",
    ],
    image: "/images/events/linyi-hardware-expo-2026.jpg",
    color: "#CA8A04",
    gradient: "from-yellow-600 via-yellow-500 to-amber-400",
    slug: "linyi-trade-logistics-fair-2026",
  },
  {
    id: "weifang",
    title: "2026 Weifang (Qingzhou) International Precision Procurement Matchmaking",
    subtitle: "Construction Machinery Industries",
    dates: "September 21–22, 2026",
    venue: "Qingzhou City, Weifang, Shandong Province",
    city: "Weifang, China",
    highlights: [
      "Direct supply from source factories — zero middleman",
      "One-stop multi-category procurement",
      "Full-process foreign trade support",
      "Construction, agriculture, mining, new energy equipment",
    ],
    benefits: [
      "700 RMB bonus subsidy",
      "Star hotels provided",
      "Free meals",
      "Free factory pick-up",
      "Transport subsidies",
      "Reserved place for buyers",
    ],
    eligibility: [
      "Construction machinery industries",
      "Overseas buyer partners welcome",
    ],
    image: "/images/events/weifang-machinery-2026.jpg",
    color: "#0369A1",
    gradient: "from-rose-700 via-pink-600 to-red-400",
    slug: "weifang-agricultural-machinery-2026",
  },
  {
    id: "digital-trade",
    title: "5th Global Digital Trade Expo 2026",
    subtitle: "Digital Trade · Connect the World",
    dates: "September 23–27, 2026",
    venue: "Hangzhou Grand Convention and Exhibition Center",
    city: "Hangzhou, China",
    highlights: [
      "National-level official platform — only digital trade expo in China",
      "150,000m² area, 1+8 sectors, full industry chain",
      "70+ high-end forums & events",
      "AI smart matching, online + offline integration",
    ],
    benefits: [
      "Travel subsidy",
      "One-on-one precise matching",
      "VIP access & service",
      "Latest tech & industry data",
      "Long-term resource connection",
    ],
    eligibility: [
      "Age: 26–60",
      "Visa: Non-student",
      "Business: Digital trade / tech / e-commerce / related industries",
    ],
    image: "/images/events/digital-trade-expo-2026.jpg",
    color: "#7C3AED",
    gradient: "from-violet-700 via-purple-600 to-fuchsia-500",
    slug: "5th-global-digital-trade-expo-2026",
  },
  {
    id: "guzhen",
    title: "2026 China (Guzhen) International Lighting Fair",
    subtitle: "Autumn Edition",
    dates: "October 22–25, 2026",
    venue: "Guzhen Convention & Exhibition Center, Zhongshan, Guangdong",
    city: "Zhongshan, China",
    highlights: [
      "150,000+ sqm exhibition area",
      "3,000+ top exhibitors",
      "100+ countries & regions, 80,000+ professional buyers",
      "Indoor, outdoor, LED, smart home, special lamp zones",
    ],
    benefits: [
      "One night's hotel accommodation",
      "Free round-trip bus transportation",
      "Exclusive fast lanes and more",
      "Bonus: 200 RMB (student) / 250 RMB (non-student visa)",
    ],
    eligibility: [
      "Age up to 26 years old (student rate)",
      "Engaged in lighting products & related industries",
      "Business owner, procurement head, or decision-maker",
      "Passport, business card & procurement needs required",
    ],
    image: "/images/events/guzhen-lighting-fair-2026.jpg",
    color: "#EAB308",
    gradient: "from-yellow-600 via-amber-500 to-orange-400",
    slug: "guzhen-lighting-fair-autumn-2026",
  },
  {
    id: "ai-macro",
    title: "Global AI Manufacturing & Electronics Expo",
    subtitle: "AIE — Macao + Zhuhai Dual Venue",
    dates: "December 3–5, 2026",
    venue: "Cotai Expo, The Venetian Macao & Zhuhai Convention Center",
    city: "Macao & Zhuhai, China",
    highlights: [
      "70,000m² exhibition area, 1,000+ top exhibitors",
      "Dual-venue: Macao for tech launch & forums, Zhuhai for trade",
      "New tech debuts, high-end summits & immersive demos",
      "Connect with leading brands & manufacturers directly",
    ],
    benefits: [
      "Free hotel stay",
      "Free daily lunch",
      "Free shuttle bus",
      "One-on-one business matching",
      "VIP entry & priority service",
    ],
    eligibility: [
      "Age: 26–60",
      "Visa: Non-student",
      "Business: AI / electronics / smart manufacturing",
      "Valid business license + purchasing authority",
    ],
    image: "/images/events/ai-macro-expo-2026.jpg",
    color: "#4F46E5",
    gradient: "from-slate-700 via-slate-600 to-gray-500",
    slug: "miecf-macao-winter-2026",
  },
];
