// Search engines show roughly 155 Latin characters (or ~80 CJK characters) of
// a meta description and rewrite ones that are much shorter or longer, so
// descriptions that come from admin-entered text are trimmed/padded here.

export const SITE_URL = "https://theuniqueexpo.com";

const CJK_RE = /[㐀-鿿]/;

export function metaDescription(text: string | null | undefined, fallback: string): string {
  let base = (text || "").replace(/\s+/g, " ").trim();
  const cjk = CJK_RE.test(base || fallback);
  const max = cjk ? 80 : 155;
  const min = cjk ? 0 : 70;

  if (!base) base = fallback;
  else if (base.length < min && fallback && !base.includes(fallback)) base = `${base} ${fallback}`;

  if (base.length <= max) return base;
  const cut = base.slice(0, max - 1);
  const lastSpace = cut.lastIndexOf(" ");
  const trimmed = (!cjk && lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).replace(/[\s,;:.\-–—]+$/, "");
  return `${trimmed}…`;
}

// An og:image that doesn't depend on a post/exhibitor having its own picture:
// the branded card generated by src/app/[locale]/opengraph-image.tsx.
export function defaultOgImage(locale: string): string {
  return `/${locale}/opengraph-image`;
}
