-- Retired: this used to reset the admin password to a fixed value on
-- every single deploy (see hostinger-deploy-remote.sh), which meant a
-- password committed in plaintext in this file's original comment was
-- silently re-applied to the live database forever, even after being
-- changed by hand. No longer run -- see 021-rotate-admin-password.sql,
-- which rotates the password once and is self-disarming.
